version: '3.7'

services:
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: ./Dockerfile-dev
    volumes:
      - ./backend:/code
      - static_data:/vol/web
      - media_data:/vol/web/media
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
    entrypoint: [ "entrypoint-dev.sh" ]

  db:
    container_name: db
    image: postgres:13.1
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: redis
    image: redis:6.0.9-alpine3.12

  celery:
    container_name: celery
    build:
      context: ./backend
      dockerfile: ./Dockerfile-dev
    volumes:
      - ./backend:/code
    env_file:
      - .env.dev
    depends_on:
      - redis
    entrypoint: [ "entrypoint-celery.sh" ]

  celery-beat:
    container_name: celery-beat
    build:
      context: ./backend
      dockerfile: ./Dockerfile-dev
    volumes:
      - ./backend:/code
    env_file:
      - .env.dev
    depends_on:
      - redis
    entrypoint: [ "entrypoint-celery-beat.sh" ]

  app:
    container_name: app
    build:
      context: ./frontend
      dockerfile: ./Dockerfile-dev
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
      - db

volumes:
  static_data:
  media_data:
  postgres_data: