version: '3.7'

services:
  production_api:
    container_name: production_api
    build:
      context: ./backend
      dockerfile: ./Dockerfile-prd
    expose:
      - 8000
    volumes:
      - static_data:/vol/web/static
      - media_data:/vol/web/media
    env_file:
      - .env.prd
    depends_on:
      - production_db
      - production_redis
    entrypoint: ["entrypoint-prd.sh"]

  production_db:
    container_name: production_db
    image: postgres:13.1
    env_file:
      - .env.prd
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  production_redis:
    container_name: production_redis
    image: redis:6.0.9-alpine3.12

  production_celery:
    container_name: production_celery
    build:
      context: ./backend
      dockerfile: ./Dockerfile-prd
    env_file:
      - .env.prd
    depends_on:
      - production_redis
    entrypoint: [ "entrypoint-celery.sh" ]

  production_celery-beat:
    container_name: production_celery-beat
    build:
      context: ./backend
      dockerfile: ./Dockerfile-prd
    env_file:
      - .env.prd
    depends_on:
      - production_redis
    entrypoint: [ "entrypoint-celery-beat.sh" ]

  production_api_proxy:
    container_name: production_api_proxy
    build: ./backend/proxy
    volumes:
      - static_data:/vol/web/static
      - media_data:/vol/web/media
    ports:
      - "8000:8000"
    depends_on:
      - production_api
      - production_db

  production_app:
    container_name: production_app
    build: ./frontend
    ports:
      - "80:80"
    env_file:
      - .env.prd
    depends_on:
      - production_api
      - production_db
      - production_api_proxy

volumes:
  static_data:
  media_data:
  postgres_data: