# Generated by Django 3.1.4 on 2020-12-31 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedinActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-datetime_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostActivityBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-datetime_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectActivityBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-datetime_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GithubActivityBase',
            fields=[
                ('projectactivitybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.projectactivitybase')),
            ],
            options={
                'ordering': ['-datetime_created'],
                'abstract': False,
            },
            bases=('feed.projectactivitybase',),
        ),
        migrations.CreateModel(
            name='PostCreatedActivity',
            fields=[
                ('postactivitybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.postactivitybase')),
            ],
            options={
                'ordering': ['-datetime_created'],
                'abstract': False,
            },
            bases=('feed.postactivitybase',),
        ),
        migrations.CreateModel(
            name='PostEditedActivity',
            fields=[
                ('postactivitybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.postactivitybase')),
            ],
            options={
                'ordering': ['-datetime_created'],
                'abstract': False,
            },
            bases=('feed.postactivitybase',),
        ),
        migrations.CreateModel(
            name='ProjectCreatedActivity',
            fields=[
                ('projectactivitybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.projectactivitybase')),
            ],
            options={
                'ordering': ['-datetime_created'],
                'abstract': False,
            },
            bases=('feed.projectactivitybase',),
        ),
        migrations.CreateModel(
            name='ProjectEditedActivity',
            fields=[
                ('projectactivitybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.projectactivitybase')),
            ],
            options={
                'ordering': ['-datetime_created'],
                'abstract': False,
            },
            bases=('feed.projectactivitybase',),
        ),
        migrations.CreateModel(
            name='GithubNewCommitActivity',
            fields=[
                ('githubactivitybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.githubactivitybase')),
            ],
            options={
                'ordering': ['-datetime_created'],
                'abstract': False,
            },
            bases=('feed.githubactivitybase',),
        ),
        migrations.CreateModel(
            name='GithubNewRepositoryActivity',
            fields=[
                ('githubactivitybase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.githubactivitybase')),
            ],
            options={
                'ordering': ['-datetime_created'],
                'abstract': False,
            },
            bases=('feed.githubactivitybase',),
        ),
    ]
