# Generated by Django 3.1.4 on 2021-01-03 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210102_1628'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcreatedactivity',
            name='project',
        ),
        migrations.RemoveField(
            model_name='posteditedactivity',
            name='project',
        ),
        migrations.AddField(
            model_name='postcreatedactivity',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='postcreatedactivity_related', to='blog.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posteditedactivity',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='posteditedactivity_related', to='blog.post'),
            preserve_default=False,
        ),
    ]
