# Generated by Django 3.1.4 on 2021-01-10 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210109_2107'),
        ('feed', '0002_auto_20210103_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeUploadedActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(default='I uploaded a new version of my resume!', max_length=200)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumeuploadedactivity_related', to='resume.resume')),
            ],
        ),
    ]
