# Generated by Django 3.1.4 on 2020-12-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='_projects',
            field=models.ManyToManyField(blank=True, related_name='keywords', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='_keywords',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Keyword'),
        ),
    ]
