# Generated by Django 3.1.4 on 2020-12-31 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201231_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'get_latest_by': 'datetime_created', 'ordering': ['_phase', '-datetime_changed']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='phase',
            new_name='_phase',
        ),
    ]
