# Generated by Django 3.1.4 on 2020-12-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201231_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['word']},
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='A short-form description for this project has yet to be added.', max_length=500),
        ),
    ]
