# Generated by Django 3.1.4 on 2020-12-31 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201231_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='_category',
        ),
    ]
