# Generated by Django 3.1.4 on 2021-01-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeoutline',
            options={'get_latest_by': ['date_uploaded']},
        ),
        migrations.AddField(
            model_name='resumeoutline',
            name='file',
            field=models.FileField(default=1, upload_to='resume/'),
            preserve_default=False,
        ),
    ]
