# Generated by Django 3.1.4 on 2021-01-09 23:55

from django.db import migrations, models
import django.db.models.deletion
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210109_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resume/')),
                ('date_uploaded', models.DateField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': ['date_uploaded'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSubsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Section Heading', max_length=500)),
                ('paragraphs', models.JSONField(default=list, encoder=resume.models.ParagraphJSONEncoder)),
                ('subtext', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='resumesection',
            name='content',
        ),
        migrations.RemoveField(
            model_name='resumesection',
            name='outline',
        ),
        migrations.AddField(
            model_name='resumesection',
            name='paragraphs',
            field=models.JSONField(default=list, encoder=resume.models.ParagraphJSONEncoder),
        ),
        migrations.AlterField(
            model_name='resumesection',
            name='heading',
            field=models.CharField(default='Section Heading', max_length=500),
        ),
        migrations.DeleteModel(
            name='ResumeOutline',
        ),
        migrations.AddField(
            model_name='resumesubsection',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='resume.resumesection'),
        ),
        migrations.AddField(
            model_name='resumesection',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resume.resume'),
        ),
    ]
