# Generated by Django 3.1.4 on 2021-01-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210109_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumesubsection',
            name='subtext',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
