# Generated by Django 3.1.4 on 2021-01-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='email_address',
            field=models.EmailField(default='johndoe@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='contactform',
            name='first_name',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AddField(
            model_name='contactform',
            name='last_name',
            field=models.CharField(default='Doe', max_length=50),
        ),
        migrations.AddField(
            model_name='contactform',
            name='message',
            field=models.TextField(default='Message body', max_length=5000),
        ),
        migrations.AddField(
            model_name='contactform',
            name='middle_initial',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
