# Generated by Django 3.1.4 on 2021-01-02 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20210102_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
