# Generated by Django 3.1.4 on 2020-12-31 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contents', models.TextField(
                    default='A long-form description for this project has yet to be added.',
                    max_length=10000)
                 ),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_changed', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='projects',
                    to='projects.project'
                )),
            ],
            options={
                'ordering': ['-datetime_created'],
                'get_latest_by': 'datetime_created',
            },
        ),
    ]
